00_loop: 00_loop.cpp
	pgc++ 00_loop.cpp -acc —Minfo=accel
01_gang: 01_gang.cpp
	pgc++ 01_gang.cpp -acc —Minfo=accel
02_parallel: 02_parallel.cpp
	pgc++ 02_parallel.cpp -acc —Minfo=accel
03_kernels: 03_kernels.cpp
	pgc++ 03_kernels.cpp -acc —Minfo=accel
04_iterator: 04_iterator.cpp
	pgc++ 04_iterator.cpp -acc —Minfo=accel
05_scope: 05_scope.cpp
	pgc++ 05_scope.cpp -acc —Minfo=accel
06_reduction: 06_reduction.cpp
	pgc++ 06_reduction.cpp -acc —Minfo=accel

